/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplicacion_java_2;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.text.Normalizer;
import java.util.StringTokenizer;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;



/*
Nombre: Jose Horacio Lopez Orellana
Carne: 1290-21-3372
Fecha: 17/08/22
Proyecto: Manejo de cadenas
*/

/**
 *
 * @author JPonce
 */
public class Programacion_II extends javax.swing.JFrame {
    JFileChooser seleccionar = new JFileChooser();
        
        File archivo;
        FileInputStream entrada;
        FileOutputStream salida;

    public Programacion_II() {
        initComponents();
    }
    
    
    public String AbrirArchivo(File archivo ){
        String documento = "";
        try{
            entrada = new FileInputStream(archivo);
            int ascci;
            while((ascci=entrada.read())!=-1){
                char caracter = (char)ascci;
                documento+=caracter;
                
            }
        } catch (Exception e){
        }
        return documento;
    }
    
    public String GuardarArchivo(File archivo,String documento){
        String mensaje=null;
        try {
            salida=new FileOutputStream(archivo);
            byte[] bytxt=documento.getBytes();
            salida.write(bytxt);
            mensaje="Archivo Guardado";
            
            } catch (Exception e) {
            }
        return mensaje;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        Texto1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Procesar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_traductor = new javax.swing.JTextArea();
        lbl_Total = new javax.swing.JLabel();
        lbl_ContarE = new javax.swing.JLabel();
        lbl_ContarI = new javax.swing.JLabel();
        lbl_ContarA = new javax.swing.JLabel();
        lbl_ContarO = new javax.swing.JLabel();
        lbl_ContarU = new javax.swing.JLabel();
        lbl_PrimeraP = new javax.swing.JLabel();
        lbl_PrimeraL = new javax.swing.JLabel();
        lbl_Longitud = new javax.swing.JLabel();
        lbl_UltimaL = new javax.swing.JLabel();
        lbl_UltimaP = new javax.swing.JLabel();
        lbl_LetraC = new javax.swing.JLabel();
        lbl_PalabraC = new javax.swing.JLabel();
        lbl_impar = new javax.swing.JLabel();
        lbl_par = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_palabra = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btn_Abrir = new javax.swing.JMenuItem();
        btn_GuardarComo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btn_copiar = new javax.swing.JMenuItem();
        btn_Cortar = new javax.swing.JMenuItem();
        btn_pegar = new javax.swing.JMenuItem();

        Texto1.setColumns(20);
        Texto1.setRows(5);
        jScrollPane3.setViewportView(Texto1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel1.setText("MANEJO DE CADENAS");

        Procesar.setBackground(new java.awt.Color(0, 255, 255));
        Procesar.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        Procesar.setText("Procesar");
        Procesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcesarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Longitud del texto: ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Total de palabras:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Primer letra del texto:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Última letra del texto:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Letra central del texto:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Primera palabra:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Palabra central:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Última palabra:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Repeticion de \"E\", \"e\" ó \"é\":");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Repeticion de \"A\", \"a\" ó \"á\":");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Repeticion de \"I\", \"i\" ó \"í\":");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Repeticion de \"O\", \"o\" ó \"ó\":");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Repeticion de \"U\", \"u\" ó \"ú\":");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Palabra con cantidad de caracteres par:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Palabra con cantidad de caracteres impar:");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("TRADUCCIÓN A CLAVE MURCIELAGO");

        txt_traductor.setBackground(new java.awt.Color(211, 255, 250));
        txt_traductor.setColumns(20);
        txt_traductor.setRows(5);
        jScrollPane2.setViewportView(txt_traductor);

        lbl_Total.setBackground(new java.awt.Color(205, 255, 212));
        lbl_Total.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lbl_Total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Total.setToolTipText("");
        lbl_Total.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_ContarE.setBackground(new java.awt.Color(205, 255, 212));
        lbl_ContarE.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lbl_ContarE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ContarE.setToolTipText("");
        lbl_ContarE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_ContarI.setBackground(new java.awt.Color(205, 255, 212));
        lbl_ContarI.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lbl_ContarI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ContarI.setToolTipText("");
        lbl_ContarI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_ContarA.setBackground(new java.awt.Color(205, 255, 212));
        lbl_ContarA.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lbl_ContarA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ContarA.setToolTipText("");
        lbl_ContarA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_ContarO.setBackground(new java.awt.Color(205, 255, 212));
        lbl_ContarO.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lbl_ContarO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ContarO.setToolTipText("");
        lbl_ContarO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_ContarU.setBackground(new java.awt.Color(205, 255, 212));
        lbl_ContarU.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lbl_ContarU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ContarU.setToolTipText("");
        lbl_ContarU.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_PrimeraP.setBackground(new java.awt.Color(205, 255, 212));
        lbl_PrimeraP.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lbl_PrimeraP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_PrimeraP.setToolTipText("");
        lbl_PrimeraP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_PrimeraL.setBackground(new java.awt.Color(205, 255, 212));
        lbl_PrimeraL.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lbl_PrimeraL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_PrimeraL.setToolTipText("");
        lbl_PrimeraL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_Longitud.setBackground(new java.awt.Color(205, 255, 212));
        lbl_Longitud.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lbl_Longitud.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Longitud.setToolTipText("");
        lbl_Longitud.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_UltimaL.setBackground(new java.awt.Color(205, 255, 212));
        lbl_UltimaL.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lbl_UltimaL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_UltimaL.setToolTipText("");
        lbl_UltimaL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_UltimaP.setBackground(new java.awt.Color(205, 255, 212));
        lbl_UltimaP.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lbl_UltimaP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_UltimaP.setToolTipText("");
        lbl_UltimaP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_LetraC.setBackground(new java.awt.Color(205, 255, 212));
        lbl_LetraC.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lbl_LetraC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_LetraC.setToolTipText("");
        lbl_LetraC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_PalabraC.setBackground(new java.awt.Color(205, 255, 212));
        lbl_PalabraC.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lbl_PalabraC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_PalabraC.setToolTipText("");
        lbl_PalabraC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_impar.setBackground(new java.awt.Color(205, 255, 212));
        lbl_impar.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lbl_impar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_impar.setToolTipText("");
        lbl_impar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_par.setBackground(new java.awt.Color(205, 255, 212));
        lbl_par.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lbl_par.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_par.setToolTipText("");
        lbl_par.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txt_palabra.setColumns(20);
        txt_palabra.setRows(5);
        jScrollPane1.setViewportView(txt_palabra);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(jLabel3))
                        .addGap(533, 533, 533)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_ContarO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_par, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_UltimaP, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_UltimaL, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Longitud, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_PrimeraL, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_PrimeraP, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_LetraC, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_PalabraC, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(168, 168, 168))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_ContarU, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_impar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_ContarE, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_ContarI, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_ContarA, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(16, 16, 16))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel17))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(Procesar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Procesar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Longitud, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(lbl_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lbl_ContarA, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_ContarE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_PrimeraL, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(lbl_ContarI, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(lbl_ContarO, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(lbl_ContarU, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel16)
                                .addGap(14, 14, 14))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lbl_impar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(lbl_par, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_PrimeraP, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(12, 12, 12))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbl_UltimaL, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_LetraC, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(lbl_PalabraC, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(lbl_UltimaP, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        jMenu1.setText("Archivo");

        btn_Abrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btn_Abrir.setText("Abrir");
        btn_Abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AbrirActionPerformed(evt);
            }
        });
        jMenu1.add(btn_Abrir);

        btn_GuardarComo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btn_GuardarComo.setText("Guardar como");
        btn_GuardarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuardarComoActionPerformed(evt);
            }
        });
        jMenu1.add(btn_GuardarComo);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");

        btn_copiar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btn_copiar.setText("Copiar");
        btn_copiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_copiarActionPerformed(evt);
            }
        });
        jMenu2.add(btn_copiar);

        btn_Cortar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btn_Cortar.setText("Cortar");
        btn_Cortar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CortarActionPerformed(evt);
            }
        });
        jMenu2.add(btn_Cortar);

        btn_pegar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btn_pegar.setText("Pegar");
        btn_pegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pegarActionPerformed(evt);
            }
        });
        jMenu2.add(btn_pegar);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcesarActionPerformed
        // variables usadas:
        String palabra = txt_palabra.getText();
        String letraU = palabra.substring(palabra.length()-1);
        String[] palabraarray = txt_palabra.getText().split(" ");
        String[] chararray = palabra.split("");
        int tamaño = 0;

        //Esto es para contar el total de palabras
        /*
        tuve que hacer un "for" ya que al momento de poder encontrar
        la palabra central un "StringTokenizer" no se podia dividi entre 2
        asi que cree un array para que este si se pudiera dividir
        en dado caso si se quita cualquiera de los, el contador de palabras
        funciona los 2 hacen la misma funcion pero el "for" sirve para poder
        encontrar la palabra central
        */
        for (int i = 0; i < palabraarray.length; i++){
            tamaño ++;

        }

        StringTokenizer st = new StringTokenizer(palabra);
        lbl_Total.setText(""+st.countTokens());

        //Esto es para tener la primera palabra del texto ingresado
        StringTokenizer tokens = new StringTokenizer(palabra);
        String primeraPalabra = tokens.nextToken();
        lbl_PrimeraP.setText(primeraPalabra);

        //Esto es para obtener la primera letra del texto ingresado
        char letra1 = palabra.charAt(0);
        lbl_PrimeraL.setText(""+letra1);

        //Esto es para tener la longitud del texto ingresado(espacios cuentan)
        int stringLength = palabra.length();
        lbl_Longitud.setText(""+stringLength);

        //Esto es para obtener la ultima letra del texto ingresado
        char [] letra2 = letraU.toCharArray();
        lbl_UltimaL.setText(""+letra2[letra2.length -1]);

        //esto es para obtener la ultima palabra del texto ingresado
        StringTokenizer ultimaP = new StringTokenizer(palabra, " ");

        String strLastToken = null;

        while( st.hasMoreTokens() ) {

            strLastToken = st.nextToken();
        }

        lbl_UltimaP.setText("" + strLastToken);

        //esto es para tener la letra central del texto
        int centro1 = stringLength/2;
        lbl_LetraC.setText(chararray[centro1]);

        //esto es para encontrar la palabra central del texto
        int centro2 = tamaño/2;
        lbl_PalabraC.setText(palabraarray[centro2]);

        //Esto es para que calcule cuantas palabras par e impar hay en el texto
        String[] valorarray = palabra.split(" ");
        int sumPar=0;
        int sumImp=0;

        for (int i = 0; i < valorarray.length; i++){
            String parimpar = valorarray[i];
            int contar = parimpar.length();

            if (contar % 2 == 0 ){
                sumPar = sumPar + 1;

            }else {
                sumImp = sumImp + 1;
            }

        }
        lbl_par.setText(Integer.toString(sumPar));
        lbl_impar.setText(Integer.toString(sumImp));

        //Esto es para contar las vocales repetidas del texto ingresado, los "int" son las variables
        int contadorA=0;
        int contadorE=0;
        int contadorI=0;
        int contadorO=0;
        int contadorU=0;

        for (int x = 0 ; x < palabra.length(); x++){
            if (palabra.charAt(x)== 'E' || palabra.charAt(x)== 'e' || palabra.charAt(x)== 'É' || palabra.charAt(x)== 'é'){
                contadorE++;
            }

        }

        lbl_ContarE.setText(""+contadorE);

        for (int x = 0 ; x < palabra.length(); x++){
            if (palabra.charAt(x)== 'A' || palabra.charAt(x)== 'a' || palabra.charAt(x)== 'Á' || palabra.charAt(x)== 'á'){
                contadorA++;
            }

        }

        lbl_ContarA.setText(""+contadorA);

        for (int x = 0 ; x < palabra.length(); x++){
            if (palabra.charAt(x)== 'O' || palabra.charAt(x)== 'o' || palabra.charAt(x)== 'Ó' || palabra.charAt(x)== 'ó'){
                contadorO++;
            }

        }

        lbl_ContarO.setText(""+contadorO);

        for (int x = 0 ; x < palabra.length(); x++){
            if (palabra.charAt(x)== 'U' || palabra.charAt(x)== 'u' || palabra.charAt(x)== 'Ú' || palabra.charAt(x)== 'ú'){
                contadorU++;
            }

        }

        lbl_ContarU.setText(""+contadorU);

        for (int x = 0 ; x < palabra.length(); x++){
            if (palabra.charAt(x)== 'I' || palabra.charAt(x)== 'i' || palabra.charAt(x)== 'Í' || palabra.charAt(x)== 'í'){
                contadorI++;
            }

        }

        lbl_ContarI.setText(""+contadorI);

        //Esto es para traducir el texto a clave mucielago
        String cadenaNormalize = Normalizer.normalize(palabra, Normalizer.Form.NFD);
        String valor2 = cadenaNormalize.replaceAll("[^\\p{ASCII}]", "");
        String s= valor2.toLowerCase();

        String av="a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z";
        String tr="7,B,3,D,5,F,8,H,4,J,K,6,0,N,9,P,Q,2,S,T,1,V,W,X,Y,Z";
        String[] abecedario = av.split(",");
        String[] traductor= tr.split(",");

        for(int i=0; i < abecedario.length; i++){
            System.out.println(abecedario[i]);
        }

        for(int i=0; i < traductor.length; i++){
            System.out.println(traductor[i]);
        }

        for (int i = 0; i <26; i++){
            s = s.replace(abecedario[i], traductor[i]);
        }
        txt_traductor.setText(s);
    }//GEN-LAST:event_ProcesarActionPerformed

    private void btn_pegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pegarActionPerformed
        // TODO add your handling code here:
        txt_palabra.paste();
    }//GEN-LAST:event_btn_pegarActionPerformed

    private void btn_GuardarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuardarComoActionPerformed
        // TODO add your handling code here:
        if(seleccionar.showDialog(null, "Guardar")==JFileChooser.APPROVE_OPTION){
            archivo=seleccionar.getSelectedFile();
            if(archivo.getName().endsWith("txt")){
                String Documento=txt_palabra.getText();
                String mensaje=GuardarArchivo(archivo, Documento);
                if(mensaje!=null){
                    JOptionPane.showMessageDialog(null, mensaje);
                }else{
                    JOptionPane.showMessageDialog(null, "Archivo no compatible");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Guardar documento de texto");
            }
        }
        
    }//GEN-LAST:event_btn_GuardarComoActionPerformed

    private void btn_AbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AbrirActionPerformed
        // TODO add your handling code here:
        if(seleccionar.showDialog(null, "Abrir")==JFileChooser.APPROVE_OPTION){
            archivo=seleccionar.getSelectedFile();
            if(archivo.canRead()){
                if(archivo.getName().endsWith("txt")){
                    String documento=AbrirArchivo(archivo);
                    txt_palabra.setText(documento);
                }else{
                    JOptionPane.showMessageDialog(null, "Archivo no compatible");
                }
            }
        }
    }//GEN-LAST:event_btn_AbrirActionPerformed

    private void btn_copiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_copiarActionPerformed
        // TODO add your handling code here:
        txt_palabra.copy();
    }//GEN-LAST:event_btn_copiarActionPerformed

    private void btn_CortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CortarActionPerformed
        // TODO add your handling code here:
        txt_palabra.cut();
    }//GEN-LAST:event_btn_CortarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Programacion_II.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Programacion_II.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Programacion_II.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Programacion_II.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Programacion_II().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Procesar;
    private javax.swing.JTextArea Texto1;
    private javax.swing.JMenuItem btn_Abrir;
    private javax.swing.JMenuItem btn_Cortar;
    private javax.swing.JMenuItem btn_GuardarComo;
    private javax.swing.JMenuItem btn_copiar;
    private javax.swing.JMenuItem btn_pegar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_ContarA;
    private javax.swing.JLabel lbl_ContarE;
    private javax.swing.JLabel lbl_ContarI;
    private javax.swing.JLabel lbl_ContarO;
    private javax.swing.JLabel lbl_ContarU;
    private javax.swing.JLabel lbl_LetraC;
    private javax.swing.JLabel lbl_Longitud;
    private javax.swing.JLabel lbl_PalabraC;
    private javax.swing.JLabel lbl_PrimeraL;
    private javax.swing.JLabel lbl_PrimeraP;
    private javax.swing.JLabel lbl_Total;
    private javax.swing.JLabel lbl_UltimaL;
    private javax.swing.JLabel lbl_UltimaP;
    private javax.swing.JLabel lbl_impar;
    private javax.swing.JLabel lbl_par;
    private javax.swing.JTextArea txt_palabra;
    private javax.swing.JTextArea txt_traductor;
    // End of variables declaration//GEN-END:variables
}
